"""Generate deterministic, entirely fictional MiniBank seed SQL."""

from __future__ import annotations

import random
from pathlib import Path

SEED = 20260715
OUTPUT = Path(__file__).with_name("002_seed.sql")


class SQLExpression(str):
    """A trusted SQL expression emitted without string quoting."""


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def insert(table: str, columns: list[str], rows: list[tuple[object, ...]]) -> str:
    values = []
    for row in rows:
        encoded = [
            str(item)
            if isinstance(item, SQLExpression)
            else quote(item)
            if isinstance(item, str)
            else str(item)
            for item in row
        ]
        values.append("(" + ", ".join(encoded) + ")")
    return f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n" + ",\n".join(values) + ";\n"


def generate() -> str:
    rng = random.Random(SEED)
    regions = ["东区", "西区", "南区", "北区", "中心区"]
    branches = [
        (branch_id, f"MiniBank示例分行{branch_id}", region)
        for branch_id, region in enumerate(regions, 1)
    ]
    customers = [
        (customer_id, rng.choice(["STANDARD", "PREMIUM", "YOUTH"]), rng.randint(1, 5))
        for customer_id in range(1, 41)
    ]
    accounts = [
        (account_id, account_id, rng.choice(["CHECKING", "SAVINGS"]), customers[account_id - 1][2])
        for account_id in range(1, 41)
    ]
    cards = [(i, i, "CREDIT" if i % 3 else "DEBIT") for i in range(1, 41)]
    merchants = [
        (merchant_id, f"虚构商户{merchant_id}", rng.choice(["餐饮", "零售", "交通", "文娱"]))
        for merchant_id in range(1, 13)
    ]
    transactions: list[tuple[object, ...]] = []
    for transaction_id in range(1, 501):
        card_id = rng.randint(1, 40)
        customer_id = card_id
        branch_id = customers[customer_id - 1][2]
        merchant_id = rng.randint(1, 12)
        amount = round(rng.uniform(8, 2800), 2)
        card_type = cards[card_id - 1][2]
        status = "POSTED" if rng.random() < 0.9 else "DECLINED"
        posted = amount if status == "POSTED" else "NULL"
        channel = rng.choice(["APP", "POS", "ATM", "WEB"])
        txn_date = SQLExpression(f"CURRENT_DATE - {rng.randint(0, 59)}")
        transactions.append(
            (
                transaction_id,
                card_id,
                customer_id,
                branch_id,
                merchant_id,
                amount,
                amount,
                posted,
                card_type,
                status,
                channel,
                txn_date,
            )
        )

    parts = ["-- Generated by data/seed/generate_seed.py with seed 20260715.\n"]
    parts.append(insert("dim_branch", ["branch_id", "branch_name", "region"], branches))
    parts.append(
        insert("dim_customer", ["customer_id", "customer_type", "home_branch_id"], customers)
    )
    parts.append(
        insert("dim_account", ["account_id", "customer_id", "account_type", "branch_id"], accounts)
    )
    parts.append(insert("dim_card", ["card_id", "account_id", "card_type"], cards))
    parts.append(
        insert(
            "dim_merchant",
            ["merchant_id", "merchant_name", "merchant_category"],
            merchants,
        )
    )
    transaction_columns = [
        "transaction_id",
        "card_id",
        "customer_id",
        "branch_id",
        "merchant_id",
        "txn_amount",
        "txn_amount_cny",
        "posted_amount",
        "card_type",
        "transaction_status",
        "transaction_channel",
        "transaction_date",
    ]
    parts.append(
        insert("dwd_card_transaction", transaction_columns, transactions).replace(
            "'NULL'", "NULL"
        )
    )
    parts.append("""
INSERT INTO dws_branch_transaction_day
SELECT branch_id, card_type, transaction_date, SUM(txn_amount_cny), COUNT(*)
FROM dwd_card_transaction WHERE transaction_status = 'POSTED'
GROUP BY branch_id, card_type, transaction_date;

INSERT INTO dws_customer_transaction_month
SELECT customer_id, date_trunc('month', transaction_date)::date,
       SUM(txn_amount_cny), COUNT(*)
FROM dwd_card_transaction WHERE transaction_status = 'POSTED'
GROUP BY customer_id, date_trunc('month', transaction_date)::date;

INSERT INTO legacy_card_transaction
SELECT transaction_id, branch_id, txn_amount FROM dwd_card_transaction WHERE transaction_id <= 10;
INSERT INTO tmp_transaction_result
SELECT transaction_id, txn_amount_cny FROM dwd_card_transaction WHERE transaction_id <= 5;
INSERT INTO test_transaction_copy
SELECT transaction_id, txn_amount_cny FROM dwd_card_transaction WHERE transaction_id <= 5;
""")
    return "\n".join(parts)


if __name__ == "__main__":
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"Wrote deterministic seed data to {OUTPUT}")
