"""Generate deterministic, entirely fictional MiniBank seed SQL."""

from __future__ import annotations

import random
from datetime import date, timedelta
from pathlib import Path


SEED = 20260715
TODAY = date(2026, 7, 15)
OUTPUT = Path(__file__).with_name("002_seed.sql")


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def insert(table: str, columns: list[str], rows: list[tuple[object, ...]]) -> str:
    values = []
    for row in rows:
        encoded = [quote(item.isoformat()) if isinstance(item, date) else quote(item) if isinstance(item, str) else str(item) for item in row]
        values.append("(" + ", ".join(encoded) + ")")
    return f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n" + ",\n".join(values) + ";\n"


def generate() -> str:
    rng = random.Random(SEED)
    branches = [(i, f"MiniBank示例分行{i}", region) for i, region in enumerate(["东区", "西区", "南区", "北区", "中心区"], 1)]
    customers = [(i, rng.choice(["STANDARD", "PREMIUM", "YOUTH"]), rng.randint(1, 5)) for i in range(1, 41)]
    accounts = [(i, i, rng.choice(["CHECKING", "SAVINGS"]), customers[i - 1][2]) for i in range(1, 41)]
    cards = [(i, i, "CREDIT" if i % 3 else "DEBIT") for i in range(1, 41)]
    merchants = [(i, f"虚构商户{i}", rng.choice(["餐饮", "零售", "交通", "文娱"])) for i in range(1, 13)]
    transactions: list[tuple[object, ...]] = []
    for transaction_id in range(1, 501):
        card_id = rng.randint(1, 40)
        customer_id = card_id
        branch_id = customers[customer_id - 1][2]
        merchant_id = rng.randint(1, 12)
        amount = round(rng.uniform(8, 2800), 2)
        card_type = cards[card_id - 1][2]
        status = "POSTED" if rng.random() < 0.9 else "DECLINED"
        posted = amount if status == "POSTED" else "NULL"
        channel = rng.choice(["APP", "POS", "ATM", "WEB"])
        txn_date = TODAY - timedelta(days=rng.randint(0, 59))
        transactions.append((transaction_id, card_id, customer_id, branch_id, merchant_id, amount, amount, posted, card_type, status, channel, txn_date))

    parts = ["-- Generated by data/seed/generate_seed.py with seed 20260715.\n"]
    parts.append(insert("dim_branch", ["branch_id", "branch_name", "region"], branches))
    parts.append(insert("dim_customer", ["customer_id", "customer_type", "home_branch_id"], customers))
    parts.append(insert("dim_account", ["account_id", "customer_id", "account_type", "branch_id"], accounts))
    parts.append(insert("dim_card", ["card_id", "account_id", "card_type"], cards))
    parts.append(insert("dim_merchant", ["merchant_id", "merchant_name", "merchant_category"], merchants))
    parts.append(insert("dwd_card_transaction", ["transaction_id", "card_id", "customer_id", "branch_id", "merchant_id", "txn_amount", "txn_amount_cny", "posted_amount", "card_type", "transaction_status", "transaction_channel", "transaction_date"], transactions).replace("'NULL'", "NULL"))
    parts.append("""
INSERT INTO dws_branch_transaction_day
SELECT branch_id, card_type, transaction_date, SUM(txn_amount_cny), COUNT(*)
FROM dwd_card_transaction WHERE transaction_status = 'POSTED'
GROUP BY branch_id, card_type, transaction_date;

INSERT INTO dws_customer_transaction_month
SELECT customer_id, date_trunc('month', transaction_date)::date,
       SUM(txn_amount_cny), COUNT(*)
FROM dwd_card_transaction WHERE transaction_status = 'POSTED'
GROUP BY customer_id, date_trunc('month', transaction_date)::date;

INSERT INTO legacy_card_transaction
SELECT transaction_id, branch_id, txn_amount FROM dwd_card_transaction WHERE transaction_id <= 10;
INSERT INTO tmp_transaction_result
SELECT transaction_id, txn_amount_cny FROM dwd_card_transaction WHERE transaction_id <= 5;
INSERT INTO test_transaction_copy
SELECT transaction_id, txn_amount_cny FROM dwd_card_transaction WHERE transaction_id <= 5;
""")
    return "\n".join(parts)


if __name__ == "__main__":
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"Wrote deterministic seed data to {OUTPUT}")

